# Site settings
title: CLEEDI - Earth science workshops
subtitle: CLEEDI
longtitle: CLEEDI - Earth science workshops
email: nobuaki@ipgp.fr
description: Webpage of the CLEEDI workshops
baseurl: "/CLEEDI" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: CLEEDI team
street_address: IPGP, 1 rue Jussieu
city: Paris
state: Paris
zip_code: 75005
country: France
#phone: (716) 555-5555

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
